### ISSUE TITLE
issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by Aya141814** [Aya141814/HelthySkinProject#17]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。
毎日のスキンケア、薬の継続期間、自分の肌の状態などを記録して、お互いに共有して褒め合うサービス（イメージ的にはスキンケアオンリーのSNS）。
自分の毎日のスキンケアを記録（投稿）して、利用者と共有する。これによって、一人では継続できなかった人も見てくれてる人がいる、という意識が出てきて継続しやすくなる。また、単純に記録をすることで自分がどれだけ続けてきたかが見られることでモチベーションが維持できるようになる。ユーザーの投稿に対していいね機能を使って相手を褒める。また、コメントなどもできるようにしてお互いにコミュニケーションを取れるようにするとさらにユーザーの継続のモチベーションの維持ができる。
自身の継続期間については、ヘッダーに簡易的な継続日数を表示しつつ、詳細情報は専用ページで見られるようにする。また、トロフィーについては詳細ページでトロフィー取得状況などを確認できるようにする。
■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/Aya141814/projects/1/views/1 
■MVPリリースまで
- [ ] 会員登録
- [ ] ログイン
- [ ] コンテンツ投稿
- [ ] 投稿一覧
- [ ] 投稿詳細
- [ ] いいね機能
- [ ] 利用規約
- [ ] プライバシーポリシー

■MVP後
- [ ] 通知機能
- [ ] 継続期間のトロフィー
- [ ] ヘッダー（継続期間の表示）
- [ ] コメント投稿機能
- [ ] コメント編集機能
- [ ] コメント削除機能
- [ ] いいね解除
- [ ] 公開範囲設定(決まったコミュニティの中だけ、など投稿の閲覧を限定できる機能)
- [ ] マイページ
- [ ] マイページ編集
- [ ] フォロー機能
- [ ] フォロー一覧
- [ ] プロフィール

■MVPレビュー依頼予定日
予定日：2024年 11月 10日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- プライバシーポリシー
- 利用規約
